### PR TITLE
Update README.md

### PR DESCRIPTION
**Pull request by Realetive**
Add information about unsupported BasicAuth.

#### Related issues

- connect to https://github.com/strongloop/loopback-connector-soap/issues/92

### Checklist

- [x] New tests added or existing tests modified to cover all changes
- [x] Code conforms with the [style guide](http://loopback.io/doc/en/contrib/style-guide.html)

### CODE REVIEW

**Comment by slnode** [comment]
Can one of the admins verify this patch? To accept patch and trigger a build add comment ".*ok\W+to\W+test.*"

**Comment by bajtos** [comment]
@raymondfeng can you please review?

**Comment by dhmlau** [comment]
@Realetive, could you please sign the CLA? https://cla.strongloop.com/agreements/strongloop/loopback-connector-soap.  Thanks!

**Comment by Realetive** [comment]
@dhmlau Done.

**Comment by dhmlau** [comment]
@Realetive, thanks for your contribution. Your PR has landed! 🎉 
Sorry about the delay.

**Pull request merged**
