### PR TITLE
test(wsdl): changed obsolete wsdl url and adapted unit tests

### PR DESCRIPTION
**Pull request by 3z3qu13l**
### Description
Adapted unit tests since public WSDL http://www.webservicex.net/stockquote.asmx?wsdl no longer responds.

#### Related issues
- connect to #93

### CODE REVIEW

**Comment by slnode** [comment]
Can one of the admins verify this patch? To accept patch and trigger a build add comment ".*ok\W+to\W+test.*"

**Comment by 3z3qu13l** [comment]
Any news about this ?

**Comment by 3z3qu13l** [comment]
Fixed indentation in test.js
But now travis is failing with node4 since loopback@3.20.0 drop support (https://github.com/strongloop/loopback/blob/master/CHANGES.md#2018-06-12-version-3200)

**Comment by virkt25** [comment]
@3z3qu13l PR merged! Thanks for your contribution!! 🎉

**Pull request merged**
