### PR TITLE
Add bearer security scheme

### PR DESCRIPTION
**Pull request by agungf**
Bearer security support,
already use it in my app to connect with agoogle Adwords SOAP service

### CODE REVIEW

**Comment by slnode** [comment]
Can one of the admins verify this patch? To accept patch and trigger a build add comment ".*ok\W+to\W+test.*"

**Comment by bajtos** [comment]
@slnode test please

**Comment by bajtos** [comment]
@agungf thank you for the pull request. Could you please add a (unit) test to verify your implementation and prevent regressions in the future?

**Comment by bajtos** [comment]
@davidcheung I am assigning this patch to you for review, please check with @raymondfeng before landing it.

**Comment by ianks** [comment]
@agungf Do you need any help writing tests for this?

**Comment by deepakrkris** [comment]
can you please add a test case for this change ?

**Comment by slnode** [comment]
Can one of the admins verify this patch? To accept patch and trigger a build add comment ".*ok\W+to\W+test.*"

**Comment by slnode** [comment]
Can one of the admins verify this patch?

**Comment by slnode** [comment]
Can one of the admins verify this patch?

**Comment by slnode** [comment]
Can one of the admins verify this patch?

**Comment by slnode** [comment]
Can one of the admins verify this patch?

**Pull request closed without merging**
