### PR TITLE
Fix readme

### PR DESCRIPTION
**Pull request by crandmck**
Changes README to use the periodic table SOAP service instead of the weather service, which is no longer available.

### CODE REVIEW

**Comment by rashmihunt** [comment]
@crandmck Fixed soap examples in loopback-example-connector - https://github.com/strongloop-community/loopback-example-connector/tree/soap

- Added periodictable-rest.js to showcase how to use loopback-connector-soap and use loopback APIs to create REST APIs. Please base this PR's code snippets based on  periodictable-rest.js
- Added periodictable-ws.js to showcase just loopback-connector-soap usage
- Updated Readme.md to reflect above changes.
- Deleted weather-rest.js and weather-ws.js since they don't work. Hence above working samples are added.
- Updated packages.json to be up to date

**Comment by crandmck** [comment]
@rashmihunt The two periodic table examples work OK, but the stock quote example does not:
```
$ node stock-ws.js 
Response:  { GetQuoteResult: 'exception' }
Response:  { GetQuoteResult: 'exception' }
```

**Comment by crandmck** [comment]
@rashmihunt I edited the README to primarily point to loopback-example-connector/soap for examples.  I left some example code in this README, but used the periodicTable example.

**Comment by rashmihunt** [comment]
@crandmck Please add a note under operations section mentioning that user needs to supply JSON stringified text of the above form by doing JSON.stringify(..) for the CLI. Also show the two line code snippet I sent it to you.. Most users trip into this issue and we should definitely fix it. 
```var operations = {
  "operations": {
    "getAtomicWeight": {
      "service": "periodictable",
      "port": "periodictableSoap",
      "operation": "GetAtomicWeight"
    },
    "getAtomicNumber": {
      "service": "periodictable",
      "port": "periodictableSoap",
      "operation": "GetAtomicNumber"
    }
  }
};

var stringifiedOps = JSON.stringify (operations);
console.log(stringifiedOps);```

**Pull request merged**
